Repository GSG-K3/event-booker, pull requests merged in 2020-06, with the labels that each got.

#141 replace normal alert with sweet alert
  client/src/Components/Common/Event/EventContainer.jsx
  client/src/Components/Layout/Base/AuthRouter.jsx
  client/src/Components/Layout/EventDetails.jsx
  client/src/Components/Layout/Login/Login.jsx
  client/src/Components/Layout/Logout.jsx
  client/src/Components/Layout/Profile/Profile.jsx
  client/src/Components/Layout/admin/AddNewEvent.jsx
  client/src/Components/Layout/admin/AdminEventDetails.jsx
  client/src/Components/Layout/admin/Attendance/TakeAttendance.jsx
  client/src/Components/Layout/admin/Home/Home.jsx
  server/controllers/event/takePlace.js
Labels: approved, enhancement

#142 Add new member
  client/src/Components/Common/Header/Burgermenu.config.jsx
  client/src/Components/Layout/Base/BaseLayout.jsx
  client/src/Components/Layout/admin/AddNewMember.jsx
  client/src/Components/Layout/admin/Attendance/TakeAttendance.jsx
  client/src/Components/Layout/admin/SignUpStyle.jsx
  server/controllers/admin/index.js
  server/controllers/admin/user/newMember.js
  server/controllers/index.js
  server/helpers/Validation.js
  server/helpers/enrollUser.js
  server/middleware/checkEmail.js
Labels: awaiting-review

#145 Add member to event
  client/src/Components/Common/Header/Burgermenu.config.jsx
  client/src/Components/Layout/Base/BaseLayout.jsx
  client/src/Components/Layout/EventDetails.jsx
  client/src/Components/Layout/SignUp/SignUp.jsx
  client/src/Components/Layout/admin/AddMemberToEvent.jsx
  client/src/Components/Layout/admin/AddNewEvent.jsx
  client/src/Components/Layout/admin/AddNewMember.jsx
  server/controllers/admin/event/addMemberToEvent.js
  server/controllers/admin/index.js
  server/controllers/admin/user/getAllMember.js
  server/controllers/admin/user/newMember.js
  server/controllers/event/takePlace.js
  server/controllers/index.js
  server/database/query/user/getAllUserByRole.js
  server/database/query/user/index.js
  server/database/query/userEvent/checkUserEvent.js
  server/database/query/userEvent/index.js
  server/helpers/enrollUser.js
  server/helpers/sendEmail.js
  server/middleware/isMemberEnrollEvent.js
Labels: approved

#147 Change password
  client/src/Components/Layout/Profile/Profile.jsx
  client/src/Components/Layout/Profile/ProfileStyles.jsx
  client/src/Components/Layout/Profile/SettingComponent/ChangePassword.jsx
  client/src/Components/Layout/Profile/Settings.jsx
  server/controllers/index.js
  server/controllers/user/changePassword.js
  server/controllers/user/index.js
  server/database/query/user/changePassword.js
  server/database/query/user/index.js
  server/helpers/Validation.js
  server/middleware/checkCurrentPassword.js
Labels: approved

#150 Refactor sign up server code
  client/src/Components/Common/Event/EventContainer.jsx
  server/controllers/admin/user/newMember.js
  server/controllers/user/signup.js
  server/database/dummyDate.js
  server/database/query/user/addUser.js
Labels: approved

#152 Profile
  client/src/Components/Layout/Profile/EdituserInfo.jsx
  client/src/Components/Layout/Profile/ProfileStyles.jsx
  client/src/Components/Layout/Profile/UserInfo.jsx
  server/controllers/index.js
  server/controllers/user/editprofile.js
  server/controllers/user/index.js
  server/database/query/user/editUserInfo.js
  server/database/query/user/index.js
  server/helpers/Validation.js
Labels: approved
