Repository GSG-K3/event-booker, pull requests merged in 2020-04, with the labels that each got.

#46 Update README.md
  README.md
Labels: approved

#47 setup project files #8
  .travis.yml
  client/.gitignore
  client/README.md
  client/eslintrc.json
  client/package-lock.json
  client/package.json
  client/prettierrc
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/index.css
  client/src/index.js
  client/src/serviceWorker.js
  eslintrc.json
  package-lock.json
  package.json
  prettierrc
  server/app.js
  server/controllers/index.js
  server/database/connection.js
  server/database/db_build.js
  server/database/db_build.sql
  server/database/query/checkUser.js
  server/server.js
Labels: Done, approved

#56 add travis config #54
  .travis.yml
  client/package.json
  package.json
Labels: awaiting-review

#64 database setup
  server/database/connection.js
  server/database/db_build.js
  server/database/db_build.sql
Labels: approved

#67 Comm comp header
  client/src/App.css
  client/src/App.js
  client/src/Components/Common/Header/BurgerMenu.jsx
  client/src/Components/Common/Header/Header.jsx
  client/src/Components/Common/Header/Logo.jsx
  client/src/Components/Common/Header/UserAvatar.jsx
  client/src/Components/Common/Header/style.jsx
  client/src/Components/Common/index.jsx
  client/src/Components/Layout/Base/AdminLayout.jsx
  client/src/Components/Layout/Base/BaseLayout.jsx
  client/src/Components/Layout/Base/UserLayout.jsx
  client/src/Components/Layout/Home.jsx
  client/src/Theme/Css/App.css
  client/src/Theme/Css/index.css
  client/src/Theme/MaterialTheme.jsx
  client/src/assets/logo.svg
  client/src/index.js
Labels: awaiting-review

#69 Edit UUID database
  client/src/Components/Layout/Home.jsx
  server/database/connection.js
  server/database/db_build.sql
  server/database/dummyDate.js
Labels: awaiting-review

#72 move the header and Main Grid to userLayout #71
  client/src/Components/Layout/Base/UserLayout.jsx
  client/src/Components/Layout/Home.jsx
Labels: approved, front-end

#74 Add Router to User , Admin Layout #73
  client/src/Components/Layout/Base/AdminLayout.jsx
  client/src/Components/Layout/Base/UserLayout.jsx
Labels: Router, approved, front-end

#76 Eventdetails
  client/src/Components/Layout/Base/UserLayout.jsx
  client/src/Components/Layout/EventDetails.jsx
Labels: approved, front-end

#75 Common component event
  client/src/Components/Common/Event/EventCardContainer.jsx
  client/src/Components/Common/Event/EventContainer.jsx
  client/src/Components/Common/Header/Header.jsx
  client/src/Components/Layout/Base/UserLayout.jsx
  client/src/Components/Layout/Home.jsx
  client/src/index.js
Labels: approved, common-component, front-end

#82 Common component event card
  client/src/Components/Common/Event/CardStyle.jsx
  client/src/Components/Common/Event/EventCard.jsx
  client/src/Components/Common/Event/EventContainer.jsx
  client/src/Components/Layout/Home.jsx
  client/src/assets/eventDefaultimg.svg
Labels: approved, common-component, front-end

#83 Eventdetails
  client/package.json
  client/src/Components/Layout/EventDetails.jsx
  package.json
  server/app.js
  server/controllers/event/getEventById.js
  server/controllers/index.js
  server/database/connection.js
  server/database/dummyDate.js
  server/database/query/event/getEventById.js
  server/helpers/responseMessage.js
  server/server.js
Labels: approved

#86 Login front end page
  client/src/Components/Layout/Base/UserLayout.jsx
  client/src/Components/Layout/EventDetails.jsx
  client/src/Components/Layout/Login.jsx
  client/src/Theme/MaterialTheme.jsx
  server/helpers/responseMessage.js
Labels: approved, front-end

#85 create back end code to get category with Events #80
  client/src/Components/Common/Event/EventCard.jsx
  client/src/Components/Common/Event/EventContainer.jsx
  client/src/Components/Common/Header/Header.jsx
  client/src/Components/Common/LoaderProgress.jsx
  client/src/Components/Layout/Base/UserLayout.jsx
  server/controllers/event/getupComingEvent.js
  server/controllers/event/index.js
  server/controllers/index.js
  server/database/query/category/getAllcategory.js
  server/database/query/event/getupComingEvent.js
Labels: approved, back-end, technical
