Repository GSG-K3/event-booker, pull requests merged in 2020-05, with the labels that each got.

#90 Loginback
  SELECT email ,password,gid,user_name,role FROM users WHERE email=test@no.test
  client/src/Components/Common/Header/BurgerMenu.jsx
  client/src/Components/Common/Header/Header.jsx
  client/src/Components/Layout/Login.jsx
  server/controllers/index.js
  server/controllers/user/getUserByName.js
  server/database/dummyDate.js
  server/database/query/login/login.js
Labels: approved, back-end

#88 the burger menu for the user #30
  client/src/Components/Common/Header/BurgerMenu.jsx
  client/src/Components/Layout/Login.jsx
Labels: in-progress

#91 Enroll in available event and take code back end
  SELECT email ,password,gid,user_name,role FROM users WHERE email=test@no.test
  client/package.json
  client/src/Components/Layout/EventDetails.jsx
  package.json
  server/controllers/event/index.js
  server/controllers/event/takePlace.js
  server/controllers/index.js
  server/controllers/user/userEvent.js
  server/database/query/checkUser.js
  server/database/query/event/takePlace.js
  server/database/query/user/getAllUserEvent.js
  server/database/query/user/getUserById.js
  server/database/query/user/getUserEventbyId.js
  server/database/query/user/index.js
  server/middleware/isAuth.js
Labels: approved, back-end

#93 Cancle place backend
  client/src/Components/Layout/EventDetails.jsx
  server/controllers/event/cancelPlace.js
  server/controllers/event/index.js
  server/controllers/index.js
  server/database/query/event/getupComingEvent.js
  server/database/query/user/deleteUserEventbyId.js
  server/database/query/user/getUserEventbyId.js
  server/database/query/user/index.js
Labels: approved, back-end, technical

#96 Back end user profile
  client/src/Components/Layout/Profile/Events.jsx
  client/src/Components/Layout/Profile/Profile.jsx
  client/src/Components/Layout/Profile/ProfileStyles.jsx
  client/src/Components/Layout/Profile/UserInfo.jsx
  server/controllers/index.js
  server/controllers/user/profile.js
Labels: approved, back-end, technical

#99 fix signup
  client/.gitignore
  client/src/Components/Layout/Base/UserLayout.jsx
  client/src/Components/Layout/SignUp.jsx
  server/controllers/index.js
  server/controllers/user/signup.js
  server/database/connection.js
  server/database/query/addUser.js
Labels: approved

#98 Take attendance front end
  .eslintrc.json
  client/.eslintrc.json
  client/.prettierrc
  client/src/Components/Layout/Base/UserLayout.jsx
  client/src/Components/Layout/admin/Attendance/Style.jsx
  client/src/Components/Layout/admin/Attendance/TakeAttendance.jsx
  client/src/Components/Layout/admin/EventMembers/CodeTextField.jsx
  client/src/Components/Layout/admin/EventMembers/EventMemberStyle.jsx
  client/src/Components/Layout/admin/EventMembers/EventMembers.jsx
Labels: approved, in-progress

#102 Addevent
  client/src/Components/Layout/AddNewEvent.jsx
  client/src/Components/Layout/Base/AdminLayout.jsx
  client/src/Components/Layout/Base/UserLayout.jsx
  client/src/Components/Layout/EventDetails.jsx
  client/src/Components/Layout/Login.jsx
  client/src/Components/Layout/SignUp.jsx
  package.json
  server/controllers/category/getcategory.js
  server/controllers/event/index.js
  server/controllers/event/postEvent.js
  server/controllers/index.js
  server/controllers/user/getUserByName.js
  server/database/db_build.sql
  server/database/query/event/postEvent.js
Labels: approved

#101 Admin home page front end
  client/src/Components/Common/Event/EventCard.jsx
  client/src/Components/Layout/Base/UserLayout.jsx
  client/src/Components/Layout/admin/Home/Home.jsx
  client/src/Components/Layout/admin/Home/HomeStyle.jsx
Labels: approved

#109 Addevent
  client/src/Components/Layout/AdminEventDetails.jsx
  client/src/Components/Layout/Base/UserLayout.jsx
  server/controllers/index.js
Labels: approved

#112 Access control
  client/src/Components/Layout/Base/AdminLayout.jsx
  client/src/Components/Layout/Base/AuthRouter.jsx
  client/src/Components/Layout/Base/BaseLayout.jsx
  client/src/Components/Layout/Base/UserLayout.jsx
  client/src/Components/Layout/Profile/Profile.jsx
  client/src/Components/Layout/admin/Home/Home.jsx
  client/src/helpers/isAuth.jsx
  server/controllers/event/takePlace.js
  server/controllers/index.js
  server/controllers/user/profile.js
  server/controllers/user/signup.js
  server/controllers/user/userEvent.js
  server/database/dummyDate.js
  server/database/query/addUser.js
  server/database/query/user/addUser.js
  server/database/query/user/index.js
  server/helpers/Constants.js
  server/helpers/responseMessage.js
  server/middleware/checkPermissions.js
  server/middleware/checkToken.js
  server/middleware/isAuth.js
Labels: approved

#117 Ui sign up
  client/package.json
  client/src/Components/Layout/Login/Login.jsx
  client/src/Components/Layout/SignUp.jsx
  client/src/Components/Layout/SignUp/SignUp.jsx
  client/src/Components/Layout/SignUp/SignUpStyle.jsx
  client/src/helpers/Validation.jsx
Labels: awaiting-review, enhancement, front-end

#118 burger menu for user and admin #31 #30
  client/src/Components/Common/Header/Burgermenu.config.jsx
  client/src/Components/Common/Header/Burgermenu.jsx
  client/src/Components/Common/Header/Header.jsx
  client/src/Components/Common/Header/UserAvatar.jsx
  client/src/Components/Common/Header/icons.css
  client/src/Components/Common/Header/style.jsx
  client/src/Components/Common/index.jsx
  client/src/Components/Layout/Base/BaseLayout.jsx
  server/middleware/checkToken.js
Labels: awaiting-review

#120 Logout code
  client/src/Components/Common/Event/EventContainer.jsx
  client/src/Components/Common/Header/Burgermenu.config.jsx
  client/src/Components/Layout/Base/BaseLayout.jsx
  client/src/Components/Layout/Login/Login.jsx
  client/src/Components/Layout/Logout.jsx
  server/controllers/index.js
  server/controllers/user/index.js
  server/controllers/user/logout.js
Labels: approved

#121 Ckeck email at sign up
  client/src/Components/Common/Header/UserAvatar.jsx
  client/src/Components/Layout/SignUp/SignUp.jsx
  client/src/Components/Layout/SignUp/SignUpStyle.jsx
  client/src/helpers/Validation.jsx
  package.json
  server/controllers/index.js
  server/controllers/user/checkUserEmail.js
  server/controllers/user/index.js
  server/controllers/user/signup.js
  server/database/query/user/addUser.js
  server/database/query/user/getUserByEmail.js
  server/database/query/user/index.js
  server/helpers/Validation.js
  server/middleware/checkEmail.js
Labels: approved

#123 update ui , add validation
  client/src/Components/Layout/admin/AddNewEvent.jsx
Labels: approved

#127 Fix menu link
  client/src/Components/Common/Header/Burgermenu.jsx
  client/src/Components/Common/Header/style.jsx
Labels: approved

#128 add width
  client/src/Components/Common/Event/EventContainer.jsx
Labels: approved

#129 Admin event page
  client/public/favicon.ico
  client/src/Components/Common/Event/CardStyle.jsx
  client/src/Components/Common/Event/EventCard.jsx
  client/src/Components/Common/Event/EventContainer.jsx
  client/src/Components/Common/Header/Burgermenu.config.jsx
  client/src/Components/Layout/Base/BaseLayout.jsx
  client/src/Components/Layout/Login/Login.jsx
  client/src/Components/Layout/admin/AddNewEvent.jsx
  client/src/Components/Layout/admin/AdminEvent.jsx
  client/src/Components/Layout/admin/AdminEventDetails.jsx
  client/src/Components/Layout/admin/Attendance/Style.jsx
  client/src/Components/Layout/admin/Attendance/TakeAttendance.jsx
  client/src/Components/Layout/admin/EventMembers/EventMemberStyle.jsx
  client/src/Components/Layout/admin/EventMembers/EventMembers.jsx
  server/controllers/admin/event/getAdminEventDetail.js
  server/controllers/admin/event/getAdminEvents.js
  server/controllers/admin/index.js
  server/controllers/event/getupComingEvent.js
  server/controllers/index.js
  server/controllers/user/login.js
  server/database/dummyDate.js
  server/database/query/event/getAllEvents.js
  server/database/query/event/getEventById.js
  server/database/query/event/getupComingEvent.js
  server/database/query/event/index.js
  server/database/query/user/addUser.js
  server/helpers/BuildCategoryEvents.js
Labels: approved

#130 fix New Event
  client/src/Components/Layout/admin/AddNewEvent.jsx
  server/database/query/event/postEvent.js
Labels: bug
